import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// Root of monorepo is parent of scripts/
const MONO_ROOT = join(__dirname, '..');

/** Chạy git, nuốt lỗi: build từ tarball / Docker không có .git vẫn chạy an toàn. */
function git(...args) {
  try {
    return execFileSync('git', args, { cwd: MONO_ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
}

// 1. Đọc package.json cha ở root
const rootPkgPath = join(MONO_ROOT, 'package.json');
const rootPkg = JSON.parse(readFileSync(rootPkgPath, 'utf8'));

// Thông tin tác giả từ package cha
const authorObj =
  typeof rootPkg.author === 'object' && rootPkg.author !== null
    ? rootPkg.author
    : {
      name: typeof rootPkg.author === 'string' ? rootPkg.author : 'Thanh Trieu Nguyen',
      username: 'konnn04',
      email: 'trieukon1011@gmail.com',
      url: 'https://github.com/konnn04',
    };

const authorName = authorObj.name || 'Thanh Trieu Nguyen';
const authorUsername = authorObj.username || 'konnn04';
const authorEmail = authorObj.email || 'trieukon1011@gmail.com';
const authorUrl = authorObj.url || 'https://github.com/konnn04';

// 2. Lấy thông tin Git
const sha = git('rev-parse', '--short=7', 'HEAD') || (process.env.RUSH_GIT_SHA ?? '').slice(0, 7);
const count = git('rev-list', '--count', 'HEAD') || (process.env.RUSH_GIT_COUNT ?? '');
const date = git('log', '-1', '--format=%cI');
const branch = git('rev-parse', '--abbrev-ref', 'HEAD');
const dirty = !!git('status', '--porcelain');

// 3. Stamp version into package.json if --stamp flag is present or in CI
const isStamp = process.argv.includes('--stamp') || process.env.CI === 'true';
const [major = '1', minor = '0'] = String(rootPkg.version ?? '1.0.0').split('.');

let currentVersion = rootPkg.version || '1.0.0';
if (isStamp && count) {
  currentVersion = `${major}.${minor}.${count}`;
  if (rootPkg.version !== currentVersion) {
    rootPkg.version = currentVersion;
    writeFileSync(rootPkgPath, JSON.stringify(rootPkg, null, 2) + '\n');
    console.log(`[stamp] Updated root package.json version -> ${currentVersion}`);
  }
}

const label = sha ? `v${currentVersion}+${sha}${dirty ? '.dirty' : ''}` : `v${currentVersion}`;

const childPackages = [
  'client/package.json',
  'server/package.json',
  'gateway/package.json',
  'packages/game-engine/package.json',
  'packages/shared/package.json',
];

for (const relPath of childPackages) {
  const fullPath = join(MONO_ROOT, relPath);
  if (existsSync(fullPath)) {
    try {
      const childPkg = JSON.parse(readFileSync(fullPath, 'utf8'));
      let changed = false;

      if (childPkg.version !== currentVersion) {
        childPkg.version = currentVersion;
        changed = true;
      }

      if (JSON.stringify(childPkg.author) !== JSON.stringify(authorObj)) {
        childPkg.author = authorObj;
        changed = true;
      }

      if (changed) {
        writeFileSync(fullPath, JSON.stringify(childPkg, null, 2) + '\n');
        console.log(`[sync] Synced version & author -> ${relPath}`);
      }
    } catch (e) {
      console.warn(`[sync] Failed to read/write ${relPath}:`, e.message);
    }
  }
}

const clientOutDir = join(MONO_ROOT, 'client', 'src', 'generated');
mkdirSync(clientOutDir, { recursive: true });

writeFileSync(
  join(clientOutDir, 'version.ts'),
  `/* AUTO-GENERATED by scripts/sync-version.mjs — derived from root package.json. Do not edit manually. */

export const BUILD = {
  /** Version derived from root package.json */
  version: ${JSON.stringify(currentVersion)},
  /** Short commit hash */
  commit: ${JSON.stringify(sha)},
  /** Git commit count */
  count: ${JSON.stringify(count || '0')},
  branch: ${JSON.stringify(branch)},
  /** Commit ISO date */
  date: ${JSON.stringify(date)},
  /** Working tree had uncommitted changes at build time */
  dirty: ${dirty},
  /** Display label for users, e.g. "v1.0.248+9f2c1ab" */
  label: ${JSON.stringify(label)},
  /** Author name */
  author: ${JSON.stringify(authorName)},
  authorUsername: ${JSON.stringify(authorUsername)},
  authorEmail: ${JSON.stringify(authorEmail)},
  authorUrl: ${JSON.stringify(authorUrl)},
} as const;
`,
);

console.log(`[version] ${label} (${authorName} <${authorEmail}> - ${authorUrl})`);
